 /******************************************************************************
 * Module: Port
 *
 * File Name: Port_PBcfg.h
 *
 * Description: Post Build Configuration Source file for TM4C123GH6PM Microcontroller - Dio Driver
 *
 * Author: Ahmed Mohamed Fathy
 ******************************************************************************/

#include "Port.h"

#ifndef PORT_PBCFG_H_
#define PORT_PBCFG_H_
   

/*
 * Module Version 1.0.0
 */
#define PORT_PBCFG_SW_MAJOR_VERSION              (1U)
#define PORT_PBCFG_SW_MINOR_VERSION              (0U)
#define PORT_PBCFG_SW_PATCH_VERSION              (0U)

/*
 * AUTOSAR Version 4.0.3
 */
#define PORT_PBCFG_AR_RELEASE_MAJOR_VERSION     (4U)
#define PORT_PBCFG_AR_RELEASE_MINOR_VERSION     (0U)
#define PORT_PBCFG_AR_RELEASE_PATCH_VERSION     (3U)

/* AUTOSAR Version checking between Dio_PBcfg.c and Dio.h files */
#if ((PORT_PBCFG_AR_RELEASE_MAJOR_VERSION != PORT_AR_RELEASE_MAJOR_VERSION)\
 ||  (PORT_PBCFG_AR_RELEASE_MINOR_VERSION != PORT_AR_RELEASE_MINOR_VERSION)\
 ||  (PORT_PBCFG_AR_RELEASE_PATCH_VERSION != PORT_AR_RELEASE_PATCH_VERSION))
  #error "The AR version of PBcfg.c does not match the expected version"
#endif

/* Software Version checking between Dio_PBcfg.c and Dio.h files */
#if ((PORT_PBCFG_SW_MAJOR_VERSION != PORT_SW_MAJOR_VERSION)\
 ||  (PORT_PBCFG_SW_MINOR_VERSION != PORT_SW_MINOR_VERSION)\
 ||  (PORT_PBCFG_SW_PATCH_VERSION != PORT_SW_PATCH_VERSION))
  #error "The SW version of PBcfg.c does not match the expected version"
#endif
   
   
 const Port_ConfigType Port_Configuration = {
                    /* PortMode0 A Configuartion  */
     PORTA,PORT_PIN0,Mode0,Digital_Pin,PORT_PIN_IN,OFF,PORT_PIN_LEVEL_LOW,PORT_PIN_DIR_CHANGEABLE,
     PORTA,PORT_PIN1,Mode0,Digital_Pin,PORT_PIN_IN,OFF,PORT_PIN_LEVEL_LOW,PORT_PIN_DIR_CHANGEABLE,
     PORTA,PORT_PIN2,Mode0,Digital_Pin,PORT_PIN_IN,OFF,PORT_PIN_LEVEL_LOW,PORT_PIN_DIR_CHANGEABLE,
     PORTA,PORT_PIN3,Mode0,Digital_Pin,PORT_PIN_IN,OFF,PORT_PIN_LEVEL_LOW,PORT_PIN_DIR_CHANGEABLE,
     PORTA,PORT_PIN4,Mode0,Digital_Pin,PORT_PIN_IN,OFF,PORT_PIN_LEVEL_LOW,PORT_PIN_DIR_CHANGEABLE,
     PORTA,PORT_PIN5,Mode0,Digital_Pin,PORT_PIN_IN,OFF,PORT_PIN_LEVEL_LOW,PORT_PIN_DIR_CHANGEABLE,
     PORTA,PORT_PIN6,Mode0,Digital_Pin,PORT_PIN_IN,OFF,PORT_PIN_LEVEL_LOW,PORT_PIN_DIR_CHANGEABLE,
     PORTA,PORT_PIN7,Mode0,Digital_Pin,PORT_PIN_IN,OFF,PORT_PIN_LEVEL_LOW,PORT_PIN_DIR_CHANGEABLE,
                    /* Port B Configuartion  */
     PORTB,PORT_PIN0,Mode0,Digital_Pin,PORT_PIN_IN,OFF,PORT_PIN_LEVEL_LOW,PORT_PIN_DIR_CHANGEABLE,
     PORTB,PORT_PIN1,Mode0,Digital_Pin,PORT_PIN_IN,OFF,PORT_PIN_LEVEL_LOW,PORT_PIN_DIR_CHANGEABLE,
     PORTB,PORT_PIN2,Mode0,Digital_Pin,PORT_PIN_IN,OFF,PORT_PIN_LEVEL_LOW,PORT_PIN_DIR_CHANGEABLE,
     PORTB,PORT_PIN3,Mode0,Digital_Pin,PORT_PIN_IN,OFF,PORT_PIN_LEVEL_LOW,PORT_PIN_DIR_CHANGEABLE,
     PORTB,PORT_PIN4,Mode0,Digital_Pin,PORT_PIN_IN,OFF,PORT_PIN_LEVEL_LOW,PORT_PIN_DIR_CHANGEABLE,
     PORTB,PORT_PIN5,Mode0,Digital_Pin,PORT_PIN_IN,OFF,PORT_PIN_LEVEL_LOW,PORT_PIN_DIR_CHANGEABLE,
     PORTB,PORT_PIN6,Mode0,Digital_Pin,PORT_PIN_IN,OFF,PORT_PIN_LEVEL_LOW,PORT_PIN_DIR_CHANGEABLE,
     PORTB,PORT_PIN7,Mode0,Digital_Pin,PORT_PIN_IN,OFF,PORT_PIN_LEVEL_LOW,PORT_PIN_DIR_CHANGEABLE,
                    /* Port C Configuartion  */
     PORTC,PORT_PIN0,Mode0,Digital_Pin,PORT_PIN_IN,OFF,PORT_PIN_LEVEL_LOW,PORT_PIN_DIR_CHANGEABLE,
     PORTC,PORT_PIN1,Mode0,Digital_Pin,PORT_PIN_IN,OFF,PORT_PIN_LEVEL_LOW,PORT_PIN_DIR_CHANGEABLE,
     PORTC,PORT_PIN2,Mode0,Digital_Pin,PORT_PIN_IN,OFF,PORT_PIN_LEVEL_LOW,PORT_PIN_DIR_CHANGEABLE,
     PORTC,PORT_PIN3,Mode0,Digital_Pin,PORT_PIN_IN,OFF,PORT_PIN_LEVEL_LOW,PORT_PIN_DIR_CHANGEABLE,	
     PORTC,PORT_PIN4,Mode0,Digital_Pin,PORT_PIN_IN,OFF,PORT_PIN_LEVEL_LOW,PORT_PIN_DIR_CHANGEABLE,
     PORTC,PORT_PIN5,Mode0,Digital_Pin,PORT_PIN_IN,OFF,PORT_PIN_LEVEL_LOW,PORT_PIN_DIR_CHANGEABLE,
     PORTC,PORT_PIN6,Mode0,Digital_Pin,PORT_PIN_IN,OFF,PORT_PIN_LEVEL_LOW,PORT_PIN_DIR_CHANGEABLE,
     PORTC,PORT_PIN7,Mode0,Digital_Pin,PORT_PIN_IN,OFF,PORT_PIN_LEVEL_LOW,PORT_PIN_DIR_CHANGEABLE,
                    /* Port D Configuartion  */
     PORTD,PORT_PIN0,Mode0,Digital_Pin,PORT_PIN_IN,OFF,PORT_PIN_LEVEL_LOW,PORT_PIN_DIR_CHANGEABLE,
     PORTD,PORT_PIN1,Mode0,Digital_Pin,PORT_PIN_IN,OFF,PORT_PIN_LEVEL_LOW,PORT_PIN_DIR_CHANGEABLE,
     PORTD,PORT_PIN2,Mode0,Digital_Pin,PORT_PIN_IN,OFF,PORT_PIN_LEVEL_LOW,PORT_PIN_DIR_CHANGEABLE,
     PORTD,PORT_PIN3,Mode0,Digital_Pin,PORT_PIN_IN,OFF,PORT_PIN_LEVEL_LOW,PORT_PIN_DIR_CHANGEABLE,
     PORTD,PORT_PIN4,Mode0,Digital_Pin,PORT_PIN_IN,OFF,PORT_PIN_LEVEL_LOW,PORT_PIN_DIR_CHANGEABLE,
     PORTD,PORT_PIN5,Mode0,Digital_Pin,PORT_PIN_IN,OFF,PORT_PIN_LEVEL_LOW,PORT_PIN_DIR_CHANGEABLE,
     PORTD,PORT_PIN6,Mode0,Digital_Pin,PORT_PIN_IN,OFF,PORT_PIN_LEVEL_LOW,PORT_PIN_DIR_CHANGEABLE,
     PORTD,PORT_PIN7,Mode0,Digital_Pin,PORT_PIN_IN,OFF,PORT_PIN_LEVEL_LOW,PORT_PIN_DIR_CHANGEABLE,
                   /* Port E Configuartion  */
     PORTE,PORT_PIN0,Mode0,Digital_Pin,PORT_PIN_IN,OFF,PORT_PIN_LEVEL_LOW,PORT_PIN_DIR_CHANGEABLE,
     PORTE,PORT_PIN1,Mode0,Digital_Pin,PORT_PIN_IN,OFF,PORT_PIN_LEVEL_LOW,PORT_PIN_DIR_CHANGEABLE,
     PORTE,PORT_PIN2,Mode0,Digital_Pin,PORT_PIN_IN,OFF,PORT_PIN_LEVEL_LOW,PORT_PIN_DIR_CHANGEABLE,
     PORTE,PORT_PIN3,Mode0,Digital_Pin,PORT_PIN_IN,OFF,PORT_PIN_LEVEL_LOW,PORT_PIN_DIR_CHANGEABLE,
     PORTE,PORT_PIN4,Mode0,Digital_Pin,PORT_PIN_IN,OFF,PORT_PIN_LEVEL_LOW,PORT_PIN_DIR_CHANGEABLE,
     PORTE,PORT_PIN5,Mode0,Digital_Pin,PORT_PIN_IN,OFF,PORT_PIN_LEVEL_LOW,PORT_PIN_DIR_CHANGEABLE,
                    /* Port F Configuartion  */
     PORTF,PORT_PIN0,Mode0,Digital_Pin,PORT_PIN_IN,OFF,PORT_PIN_LEVEL_LOW,PORT_PIN_DIR_CHANGEABLE,
     PORTF,PORT_PIN1,Mode0,Digital_Pin,PORT_PIN_OUT,OFF,PORT_PIN_LEVEL_LOW, PORT_PIN_DIR_CHANGEABLE,  // LED
     PORTF,PORT_PIN2,Mode0,Digital_Pin,PORT_PIN_IN,OFF,PORT_PIN_LEVEL_LOW,PORT_PIN_DIR_CHANGEABLE,
     PORTF,PORT_PIN3,Mode0,Digital_Pin,PORT_PIN_IN,OFF,PORT_PIN_LEVEL_LOW,PORT_PIN_DIR_CHANGEABLE,
     PORTF,PORT_PIN4,Mode0,Digital_Pin,PORT_PIN_IN,PULL_UP,PORT_PIN_LEVEL_LOW,PORT_PIN_DIR_CHANGEABLE,  // Button
              
};

   
#endif   /* PORT_PBcfg_H */
   
